import java.io.InputStream;
import java.io.OutputStream;

/**
 * <b>Lexical Analyzer</b><br>
 * 
 * This class represents a <b>Lexical Analyzer</b> based on the 
 * automatons generated by the {@link GLA}.<br>
 * 
 * It reads the automatons, and analyzes the input based on the automatons
 * that it's read.
 * 
 * @author fiilip
 *
 */
public class LA {

	/**
	 * Program entry - point.
	 * 
	 * @param args Not used.
	 */
	public static void main(String[] args) {
		
	}
	
	/**
	 * Input stream to be analyzed by the <b>Lexical Analyzer</b>.
	 */
	private final InputStream istream;
	
	/**
	 * Output stream for the resulting analysis.
	 */
	private final OutputStream ostream;
	
	/**
	 * Public constructor.<br>
	 * 
	 * Creates the new instance of {@link LA}.
	 * 
	 * @param istream	Input stream to be analyzed.
	 * @param ostream	Output stream for the resulting analysis.
	 */
	public LA(InputStream istream, OutputStream ostream) {
		this.istream = istream;
		this.ostream = ostream;
	}
	
	/**
	 * Performs the lexical analysis of the input stream.
	 * 
	 * @param filename	Name of the file to be lexically analyzed.
	 */
	public void analyze(String filename) {
		
	}
}
